Vagrant.require_plugin('vagrant-simple_cloud')

Vagrant.configure('2') do |config|
  config.vm.define "test" do |t|
    t.vm.provider :simple_cloud do |provider, override|
      override.ssh.private_key_path = 'test_id_rsa'
      override.vm.box = 'simple_cloud'
      override.vm.hostname = 'test'
      override.vm.provision :shell, :path => 'scripts/provision.sh'

      provider.token = ENV['DO_TOKEN']
    end
  end
end
